"use strict";
(function(){
const KEY="wagerwell-demo-v1";
const fmt=n=>Math.floor(Number(n)||0).toLocaleString("ko-KR");
const causes=[
{id:0,emoji:"🐾",title:"보호소 겨울 담요",tag:"PROJECT 001 · ANIMAL CARE",target:50000,base:18500,style:"a",desc:"가상의 유기동물 보호소에 겨울 담요를 마련하는 프로젝트. 코인이 모일수록 보호소가 더 따뜻해집니다."},
{id:1,emoji:"🍱",title:"따뜻한 한 끼 500인분",tag:"PROJECT 002 · MEAL SUPPORT",target:75000,base:30750,style:"b",desc:"게임 속 무료급식소에 한 끼 식사를 지원하는 프로젝트. 실제 식사나 기부금이 전달되지는 않습니다."},
{id:2,emoji:"📚",title:"작은 도서관 새 책",tag:"PROJECT 003 · EDUCATION",target:90000,base:42900,style:"c",desc:"가상 도서관의 빈 책장을 새 책들로 채우는 프로젝트. 이 프로젝트의 모든 변화는 게임 속에서만 이루어집니다."},
{id:3,emoji:"🌊",title:"바다 쓰레기 수거",tag:"PROJECT 004 · OCEAN",target:120000,base:53100,style:"d",desc:"가상의 해변에서 쓰레기를 수거하고 바다 생물의 서식지를 복원하는 프로젝트."}
];
const seed=()=>({coins:10000,donations:[0,0,0,0],history:[],claimed:"",total:0,count:0});
let s=seed();try{let v=JSON.parse(localStorage.getItem(KEY));if(v&&typeof v==="object"){s={...seed(),...v};s.coins=Math.max(0,Math.min(1e9,Math.floor(Number(s.coins)||0)));s.donations=causes.map((_,i)=>Math.max(0,Math.floor(Number(v.donations&&v.donations[i])||0)));s.history=Array.isArray(v.history)?v.history.slice(0,20):[];s.total=s.donations.reduce((a,b)=>a+b,0);s.count=Math.max(0,Math.floor(Number(s.count)||0));}}catch(_){}
let modalType="",currentCause=0,bj=null,baccaratResult=null,toastTimer=null;
const el=id=>document.getElementById(id);
function store(){try{localStorage.setItem(KEY,JSON.stringify(s));}catch(_){}}
function log(title,delta,detail){s.history.unshift({title,delta,detail,ts:new Date().toLocaleString("ko-KR")});s.history=s.history.slice(0,20);}
function showToast(msg){const t=el("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2800);}
function wallet(){el("balance").textContent=fmt(s.coins);el("sideBalance").textContent=fmt(s.coins);el("impactTotal").textContent=fmt(s.total);el("impactCount").textContent=fmt(s.count);el("claimBtn").textContent=s.coins<500?"+ 무료 구제 코인 받기":s.claimed===new Date().toLocaleDateString("en-CA")?"오늘의 무료 코인 수령 완료":"+ 무료 코인 받기";}
function save(){store();wallet();renderHistory();renderCauses();}
function expense(n){if(!Number.isSafeInteger(n)||n<=0||n>s.coins){showToast("보유 코인보다 큰 금액은 사용할 수 없어요.");return false;}s.coins-=n;return true;}
function amount(){let n=Number(el("betInput")?.value);if(!Number.isSafeInteger(n)||n<1||n>1000000){showToast("베팅 금액은 1~1,000,000 코인입니다.");return null;}return n;}
function pay(n){s.coins=Math.min(1e9,s.coins+n);}
function betControl(label="BET AMOUNT"){return '<div class="modal-balance"><span>AVAILABLE VIRTUAL COINS</span><strong>ⓒ <span id="modalCoins">'+fmt(s.coins)+'</span></strong></div><div class="bet-row"><label>'+label+'<input id="betInput" aria-label="베팅 금액" type="number" min="1" max="1000000" step="1" value="'+Math.min(100,Math.max(1,s.coins))+'"></label><button class="quick" data-bet="100">100</button><button class="quick" data-bet="500">500</button><button class="quick" data-bet="max">MAX</button></div>';}
function syncModalCoins(){if(el("modalCoins"))el("modalCoins").textContent=fmt(s.coins);}
function result(msg){if(el("result"))el("result").textContent=msg;}
function open(title,kicker,html,type){modalType=type;el("modalTitle").textContent=title;el("modalKicker").textContent=kicker;el("modalBody").innerHTML=html;el("modal").classList.remove("hidden");el("modal").setAttribute("aria-hidden","false");el("closeModal").focus();}
function close(){el("modal").classList.add("hidden");el("modal").setAttribute("aria-hidden","true");modalType="";bj=null;}
function recordGame(name,stake,payout,detail){pay(payout);log(name,payout-stake,detail);save();syncModalCoins();}
function renderHistory(){const root=el("historyList");root.innerHTML="";if(!s.history.length){const p=document.createElement("p");p.className="hint";p.textContent="아직 거래 기록이 없습니다. 게임을 플레이하거나 광고 배너에 코인을 사용해 보세요.";root.append(p);return;}s.history.slice(0,8).forEach(h=>{const row=document.createElement("div");row.className="ledger-row";const left=document.createElement("div");const b=document.createElement("b");b.textContent=String(h.title||"GAME");const sm=document.createElement("small");sm.textContent=String(h.ts||"")+" · "+String(h.detail||"");left.append(b,sm);const val=document.createElement("strong");val.className=h.delta<0?"negative":"";val.textContent=(h.delta>=0?"+":"")+fmt(h.delta)+" C";row.append(left,val);root.append(row);});}
function renderCauses(){const root=el("causeGrid");root.innerHTML="";causes.forEach(c=>{const progress=Math.min(c.target,c.base+s.donations[c.id]),pct=Math.round(progress/c.target*100);const card=document.createElement("button");card.className="cause-card";card.dataset.cause=String(c.id);card.innerHTML='<div class="cause-cover '+c.style+'"><span>'+c.emoji+'</span><div><small>'+c.tag+'</small><b>'+c.title+'</b></div></div><div class="cause-meta"><div><span>PROJECT FUNDING</span><b>'+fmt(progress)+' / '+fmt(c.target)+' C</b></div><div class="progress"><span style="width:'+pct+'%"></span></div><small>'+(pct>=100?"프로젝트 목표 달성 ✓":"달성률 "+pct+"% · 후원하기 ↗")+'</small></div>';root.append(card);});}
function claim(){const today=new Date().toLocaleDateString("en-CA");let n=0;if(s.coins<500){n=2000;}else if(s.claimed!==today){n=3000;s.claimed=today;}else{showToast("오늘의 무료 코인은 이미 받았어요. 잔액이 500 미만이면 구제 코인을 받을 수 있어요.");return;}pay(n);log("무료 가상 코인",n,"현금 가치 없음");save();showToast(fmt(n)+" 가상 코인이 지급됐어요.");}
function openCause(id){const c=causes[id];if(!c)return;currentCause=id;const progress=Math.min(c.target,c.base+s.donations[id]);const remaining=c.target-progress;open(c.title,"VIRTUAL CAUSE / "+c.tag,betControl("SUPPORT COINS")+'<div class="cause-detail-icon">'+c.emoji+'</div><h3 class="cause-detail-title">'+c.title+'</h3><p class="cause-description">'+c.desc+'</p><div class="cause-amount"><span>현재 진행액</span><span>'+fmt(progress)+' / '+fmt(c.target)+' C</span></div><div class="progress"><span style="width:'+(progress/c.target*100)+'%"></span></div><div class="action-row"><button id="donateBtn" class="play-btn" '+(!remaining?"disabled":"")+'>가상 코인 보내기 ↗</button></div><div id="result" class="result">'+(remaining?"남은 목표 "+fmt(remaining)+" C":"목표 달성! 다른 프로젝트를 찾아보세요.")+'</div><p class="hint">ⓘ 게임 안의 가상 프로젝트입니다. 실제 기부나 외부 송금이 발생하지 않습니다.</p>',"cause");const inp=el("betInput");inp.max=Math.max(1,remaining);inp.value=Math.min(1000,Math.max(1,remaining),Math.max(1,s.coins));el("donateBtn").onclick=()=>{const requested=amount();if(!requested)return;const room=Math.max(0,c.target-c.base-s.donations[id]);if(!room){showToast("이미 달성한 프로젝트입니다.");return;}const n=Math.min(requested,room);if(!expense(n))return;s.donations[id]+=n;s.total+=n;s.count+=1;log(c.title,-n,"가상 선행 프로젝트에 사용");save();showToast(fmt(n)+"코인으로 가상의 선행에 참여했어요.");openCause(id);};}
function openSlots(){open("LUCKY 777","GAME 01 / SLOTS",betControl()+'<div class="reels"><div class="reel" id="reel0">7</div><div class="reel" id="reel1">7</div><div class="reel" id="reel2">7</div></div><div class="action-row"><button id="spin" class="play-btn">SPIN ▶</button></div><div id="result" class="result">세 칸이 같으면 당첨! 777 = 25배 · 🍒🍒🍒 = 12배 · 기타 3개 = 6배 · 체리 2개 = 2배</div><p class="hint">배당은 원금을 포함한 지급액입니다. 각 기호는 동일 확률로 등장합니다.</p>',"slots");el("spin").onclick=()=>{const n=amount();if(!n||!expense(n))return;const symbols=["7","🍒","🍋","🔔","⭐","🍀"];const rr=[0,1,2].map(()=>symbols[Math.floor(Math.random()*symbols.length)]);rr.forEach((v,i)=>el("reel"+i).textContent=v);let x=0;if(rr.every(v=>v==="7"))x=25;else if(rr.every(v=>v==="🍒"))x=12;else if(rr.every(v=>v===rr[0]))x=6;else if(rr.filter(v=>v==="🍒").length===2)x=2;const prize=n*x;recordGame("LUCKY 777",n,prize,rr.join(" "));result(x?"당첨! "+fmt(prize)+"코인이 지급됐어요. (x"+x+")":"이번엔 미당첨. 다음 기회를 노려보세요.");};}
const rank=card=>Math.min(10,card.r);function deck(){const cards=[];for(let d=0;d<4;d++)for(let r=1;r<=13;r++)cards.push({r,s:["♠","♥","♦","♣"][d]});for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}return cards;}
function handTotal(h){let v=0,a=0;h.forEach(c=>{v+=c.r===1?11:rank(c);if(c.r===1)a++;});while(v>21&&a){v-=10;a--;}return v;}
function cardsHtml(hand,hide=false){return hand.map((c,i)=>hide&&i===1?'<span class="card back">WW</span>':'<span class="card '+(c.s==="♥"||c.s==="♦"?"red":"")+'">'+(["A","2","3","4","5","6","7","8","9","10","J","Q","K"][c.r-1])+c.s+'</span>').join("");}
function bjView(){const running=bj&&bj.active;let html=betControl()+'<div class="table-felt"><small>DEALER '+(bj?(running?"?":handTotal(bj.dealer)):"—")+'</small><div class="hand" id="dealerHand">'+(bj?cardsHtml(bj.dealer,running):'<span class="hint">대기 중</span>')+'</div><small>PLAYER '+(bj?handTotal(bj.player):"—")+'</small><div class="hand" id="playerHand">'+(bj?cardsHtml(bj.player):'<span class="hint">카드를 받으세요</span>')+'</div></div><div class="action-row">'+(running?'<button class="play-btn" id="hit">HIT +</button><button class="quick" id="stand">STAND ■</button>':'<button class="play-btn" id="deal">DEAL CARDS ▶</button>')+'</div><div id="result" class="result">'+(bj?bj.message:"21에 가까운 패로 딜러를 이겨 보세요. 딜러는 소프트 17을 포함해 17 이상에서 스탠드합니다.")+'</div><p class="hint">일반 승리 1:1 · 내추럴 블랙잭 3:2 · 무승부는 원금 반환. 한 판당 1~1,000,000 C.</p>';el("modalBody").innerHTML=html;if(running){el("betInput").disabled=true;el("hit").onclick=()=>{bj.player.push(bj.cards.pop());if(handTotal(bj.player)>21)finishBJ();else bjView();};el("stand").onclick=finishBJ;}else el("deal").onclick=startBJ;}
function openBlackjack(){bj=null;open("BLACKJACK","GAME 03 / TABLE","", "blackjack");bjView();}
function startBJ(){const n=amount();if(!n||!expense(n))return;const cards=deck();bj={bet:n,cards,player:[cards.pop(),cards.pop()],dealer:[cards.pop(),cards.pop()],active:true,message:"카드를 더 받을까요?"};save();if(handTotal(bj.player)===21||handTotal(bj.dealer)===21)finishBJ();else bjView();}
function finishBJ(){if(!bj||!bj.active)return;bj.active=false;const pt=handTotal(bj.player);let dt=handTotal(bj.dealer);const naturalP=bj.player.length===2&&pt===21,naturalD=bj.dealer.length===2&&dt===21;if(pt<=21&&!naturalP&&!naturalD)while(dt<17){bj.dealer.push(bj.cards.pop());dt=handTotal(bj.dealer);}let prize=0,label="패배";if(pt>21){label="버스트! 패배";}else if(naturalP&&!naturalD){prize=Math.floor(bj.bet*2.5);label="BLACKJACK! 3:2 승리";}else if(naturalD&&!naturalP){label="딜러 블랙잭";}else if(pt===dt){prize=bj.bet;label="PUSH · 무승부";}else if(dt>21||pt>dt){prize=bj.bet*2;label="승리!";}bj.message=label+" | PLAYER "+pt+" : DEALER "+dt+" | 지급 "+fmt(prize)+" C";recordGame("BLACKJACK",bj.bet,prize,bj.message);bjView();}
function baccaratScore(h){return h.reduce((n,c)=>n+(c.r===1?1:c.r>=10?0:c.r),0)%10;}
function baccaratRound(cards){const p=[cards.pop(),cards.pop()],b=[cards.pop(),cards.pop()];const p2=baccaratScore(p),b2=baccaratScore(b);if(p2>=8||b2>=8)return{p,b,pScore:p2,bScore:b2};let third=null;if(p2<=5){third=cards.pop();p.push(third);}if(third===null){if(b2<=5)b.push(cards.pop());}else{const x=third.r===1?1:third.r>=10?0:third.r;if(b2<=2||(b2===3&&x!==8)||(b2===4&&x>=2&&x<=7)||(b2===5&&x>=4&&x<=7)||(b2===6&&(x===6||x===7)))b.push(cards.pop());}return{p,b,pScore:baccaratScore(p),bScore:baccaratScore(b)};}
function openBaccarat(){baccaratResult=null;open("BACCARAT","GAME 02 / TABLE",betControl()+'<div class="choices"><button class="choice selected" data-side="player">PLAYER · 2.00x</button><button class="choice" data-side="banker">BANKER · 1.95x</button><button class="choice" data-side="tie">TIE · 9.00x</button></div><div class="table-felt"><small>PLAYER <span id="pScore">—</span></small><div class="hand" id="pCards"><span class="hint">카드 대기</span></div><small>BANKER <span id="bScore">—</span></small><div class="hand" id="bCards"><span class="hint">카드 대기</span></div></div><div class="action-row"><button id="bacDeal" class="play-btn">DEAL ▶</button></div><div id="result" class="result">플레이어 / 뱅커 / 타이 중 하나를 선택하세요.</div><p class="hint">플레이어·뱅커 베팅 시 타이는 원금 반환. 뱅커 승리 배당 1.95배(수수료 5%). 뱅커의 세 번째 카드는 정식 규칙을 따릅니다.</p>',"baccarat");let choice="player";el("modalBody").querySelectorAll("[data-side]").forEach(btn=>btn.onclick=()=>{choice=btn.dataset.side;el("modalBody").querySelectorAll("[data-side]").forEach(x=>x.classList.toggle("selected",x===btn));});el("bacDeal").onclick=()=>{const n=amount();if(!n||!expense(n))return;const r=baccaratRound(deck());el("pCards").innerHTML=cardsHtml(r.p);el("bCards").innerHTML=cardsHtml(r.b);el("pScore").textContent=r.pScore;el("bScore").textContent=r.bScore;const winner=r.pScore===r.bScore?"tie":r.pScore>r.bScore?"player":"banker";let prize=0;if(winner===choice)prize=choice==="tie"?n*9:choice==="banker"?Math.floor(n*1.95):n*2;else if(winner==="tie"&&choice!=="tie")prize=n;recordGame("BACCARAT",n,prize,"PLAYER "+r.pScore+" : BANKER "+r.bScore+" / "+winner.toUpperCase());result((winner===choice?"당첨!":winner==="tie"&&choice!=="tie"?"타이 · 원금 반환":"미당첨")+" | 결과 "+winner.toUpperCase()+" | 지급 "+fmt(prize)+" C");};}
const redNums=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);const colorOf=n=>n===0?"green":redNums.has(n)?"red":"black";
function openRoulette(){open("ROULETTE","GAME 04 / TABLE",betControl()+'<div class="choices"><button class="choice selected" data-roulette="red">RED · 2x</button><button class="choice" data-roulette="black">BLACK · 2x</button><button class="choice" data-roulette="number">SINGLE NUMBER · 36x</button></div><label id="numberBox" class="hint" style="display:none">0~36 중 하나 선택 <input id="targetNumber" type="number" min="0" max="36" value="7" style="display:block;margin-top:7px;padding:10px;width:100px;background:#0d1814;border:1px solid #456249;color:#fff"></label><div class="roulette-result" id="rouletteBall">?</div><div class="action-row"><button id="rouletteSpin" class="play-btn">SPIN WHEEL ▶</button></div><div id="result" class="result">유럽식 룰렛 · 0~36 숫자 37개 중 하나가 같은 확률로 등장합니다.</div><p class="hint">RED / BLACK 2배, 단일 숫자 36배 (원금 포함). 초록색 0에서는 색상 베팅이 지게 됩니다.</p>',"roulette");let type="red";el("modalBody").querySelectorAll("[data-roulette]").forEach(btn=>btn.onclick=()=>{type=btn.dataset.roulette;el("numberBox").style.display=type==="number"?"block":"none";el("modalBody").querySelectorAll("[data-roulette]").forEach(x=>x.classList.toggle("selected",x===btn));});el("rouletteSpin").onclick=()=>{const n=amount();if(!n)return;let target=null;if(type==="number"){target=Number(el("targetNumber").value);if(!Number.isInteger(target)||target<0||target>36){showToast("번호는 0~36 중 선택하세요.");return;}}if(!expense(n))return;const ball=Math.floor(Math.random()*37),color=colorOf(ball),win=type==="number"?ball===target:color===type,prize=win?n*(type==="number"?36:2):0;const dot=el("rouletteBall");dot.className="roulette-result "+color;dot.textContent=String(ball);recordGame("ROULETTE",n,prize,"BALL "+ball+" / "+color.toUpperCase());result((win?"당첨!":"미당첨")+" | "+ball+" "+color.toUpperCase()+" | 지급 "+fmt(prize)+" C");};}
function startGame(g){if(g==="slots")openSlots();else if(g==="baccarat")openBaccarat();else if(g==="blackjack")openBlackjack();else if(g==="roulette")openRoulette();}
document.addEventListener("click",e=>{const b=e.target.closest("[data-game],[data-scroll],[data-cause],[data-close],[data-bet]");if(!b)return;if(b.dataset.close){close();return;}if(b.dataset.bet){const input=el("betInput");if(!input||input.disabled)return;input.value=b.dataset.bet==="max"?Math.max(1,Math.min(1000000,s.coins)):b.dataset.bet;return;}if(b.dataset.game){startGame(b.dataset.game);return;}if(b.dataset.cause!==undefined){openCause(Number(b.dataset.cause));return;}if(b.dataset.scroll){el(b.dataset.scroll)?.scrollIntoView({behavior:"smooth",block:"start"});}});
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!el("modal").classList.contains("hidden"))close();if((e.key==="Enter"||e.key===" ")&&e.target.matches("[role=button][data-cause]")){e.preventDefault();openCause(Number(e.target.dataset.cause));}});
el("closeModal").onclick=close;el("claimBtn").onclick=claim;el("resetBtn").onclick=()=>{if(!confirm("현재 브라우저에 저장된 코인·게임 기록·가상 후원 내역을 초기화할까요?"))return;s=seed();save();showToast("데모 데이터를 초기화했어요.");};
wallet();renderCauses();renderHistory();
el("tickerText").textContent="● LIVE | 무료 가상 코인 지급 중   ◆   보호소 담요 프로젝트 OPEN   ◆   바카라 · 블랙잭 · 슬롯 · 룰렛 정상 운영 중   ◆   모든 선행은 게임 속 가상 프로젝트입니다.";
})();